;;; SPDX-License-Identifier: GPL-3.0-or-later WITH Classpath-exception-2.0
(load (merge-pathnames "../load.lisp" *load-truename*))
(load (merge-pathnames "check.lisp" *load-truename*))
(let* ((key-path (merge-pathnames "test.identity" *apk-test-root*))
       (identity (progn (format t "Creating identity~%") (egcl-apk:create-identity key-path)))
       (restored (progn (format t "Reloading identity~%") (egcl-apk:load-identity key-path)))
       (entries (list (cons "AndroidManifest.xml" (egcl-apk:manifest :package "org.egcl.apktest" :label "Lisp é😀"))
                      ;; Cross the v2 1 MiB chunk boundary, then start another ZIP section.
                      (cons "assets/payload.bin" (make-array (+ 1048576 23) :element-type '(unsigned-byte 8) :initial-element 42))
                      (cons "lib/arm64-v8a/test.so" #(1 2 3)))))
  (assert (equalp (egcl-apk::signing-identity-certificate identity)
                 (egcl-apk::signing-identity-certificate restored)))
  (assert (handler-case (progn (egcl-apk:create-identity key-path) nil) (error () t)))
  (format t "Signing chunk-boundary APK~%")
  (egcl-apk:write-apk (merge-pathnames "signed.apk" *apk-test-root*) entries :identity identity)
  (egcl-apk:write-apk (merge-pathnames "signed-again.apk" *apk-test-root*) entries :identity restored))
(format t "APK-SIGNING-OK~%")
(when (uiop:getenv "EGCL_APK_RUNTIME")
  (egcl-apk:build-apk (uiop:getenv "EGCL_APK_TEST_PROJECT") (uiop:getenv "EGCL_APK_RUNTIME")
                     :output (merge-pathnames "demo.apk" *apk-test-root*)
                     :identity-path (merge-pathnames "test.identity" *apk-test-root*))
  (format t "APK-DEMO-OK~%"))
