;;; Run after loading the pinned library. Assert frames, not just successful LOAD.
#+sbcl (declaim (optimize (debug 3)))
(defun tb-capture (value)
  (declare (ignorable value))
  (let ((frames nil))
    (trivial-backtrace:map-backtrace (lambda (frame) (push frame frames)))
    (prog1 (nreverse frames) (length value))))
(defun tb-middle (value capture)
  (if capture (tb-capture value) value))
(defun tb-find (name frames)
  (find-if (lambda (frame)
             (let ((function (trivial-backtrace::frame-func frame)))
               (and function (search name (string-upcase (princ-to-string function))))))
           frames))
(defun tb-print-leaf ()
  (with-output-to-string (stream)
    (trivial-backtrace:print-backtrace-to-stream stream)))
(defun tb-string-leaf () (trivial-backtrace:backtrace-string))

(format t "TB-CHECK: warmup~%")
(dotimes (i 100) (assert (= 42 (tb-middle 42 nil))))
#+egcl
(let* ((tier (or (egcl-ext:getenv "EGCL_FORCE_TIER") "t0"))
       (expected (cond ((equal tier "t1") 1) ((equal tier "t2") 2) (t 0))))
  (assert (= expected (egcl-ext:function-tier 'tb-middle))))
(format t "TB-CHECK: structured~%")
(let* ((value (list "argument retained" 42))
       (frames (tb-middle value t))
       (leaf (tb-find "TB-CAPTURE" frames))
       (middle (tb-find "TB-MIDDLE" frames)))
  (assert leaf) (assert middle)
  (assert (< (position leaf frames) (position middle frames)))
  #+egcl
  (let ((variables (trivial-backtrace::frame-vars leaf)))
    ;; Keep VALUE live across capture so both native tiers retain a managed
    ;; argument home, then require the same identity and retention contract.
    (assert variables)
    (assert (equal "Arg-0" (trivial-backtrace::var-name (first variables))))
    (assert (eq value (trivial-backtrace::var-value (first variables))))
    (setf (second value) 43)
    (dotimes (i 1000) (list i i i))
    (assert (equal '("argument retained" 43)
                   (trivial-backtrace::var-value (first variables))))))

(format t "TB-CHECK: print-stream~%")
(assert (search "TB-PRINT-LEAF" (tb-print-leaf)))
(format t "TB-CHECK: structured-string~%")
(assert (search "TB-STRING-LEAF" (tb-string-leaf)))
(format t "TB-CHECK: destinations~%")
(let* ((condition (make-condition 'simple-error :format-control "PORT-CONDITION"))
       (text (trivial-backtrace:print-backtrace condition :output nil)))
  (assert (stringp text))
  (assert (search "PORT-CONDITION" text))
  (let ((stream (make-string-output-stream)))
    (assert (null (trivial-backtrace:print-backtrace condition :output stream)))
    (assert (search "PORT-CONDITION" (get-output-stream-string stream))))
  (let ((terminal (make-string-output-stream)))
    (let ((*terminal-io* terminal))
      (assert (stringp (trivial-backtrace:print-backtrace condition :output nil :verbose t))))
    (assert (search "PORT-CONDITION" (get-output-stream-string terminal))))
  (trivial-backtrace:print-backtrace condition :output "trace-output.txt" :if-exists :supersede)
  (let ((before (with-open-file (stream "trace-output.txt")
                  (let ((text (make-string (file-length stream))))
                    (read-sequence text stream)
                    text))))
    (trivial-backtrace:print-backtrace condition :output "trace-output.txt" :if-exists :append)
    (with-open-file (stream "trace-output.txt")
      (let ((after (make-string (file-length stream))))
        (read-sequence after stream)
        (assert (> (length after) (length before)))
        (assert (string= before after :end2 (length before)))
        (assert (search "PORT-CONDITION" after :start2 (length before)))))))
(format t "TB-CHECK: live-condition~%")
(defun tb-signal-leaf () (error "LIVE-CONDITION"))
(let ((text nil))
  (handler-case
      (handler-bind ((error (lambda (condition)
                             (setf text (trivial-backtrace:print-backtrace condition :output nil)))))
        (tb-signal-leaf))
    (error () nil))
  (assert (search "LIVE-CONDITION" text))
  (assert (search "TB-SIGNAL-LEAF" text)))
(format t "TRIVIAL-BACKTRACE-PASS~%")
