(require :asdf)
(asdf:load-asd (truename "lib/torcl-jvm/torcl-jvm.asd"))
(asdf:load-system :torcl-jvm)
(defun check-java (name expected actual)
  (format t "~A: ~S~%" name actual)
  (finish-output)
  (unless (equal expected actual) (error "~A expected ~S" name expected)))
(java:define-class array-list "java.util.ArrayList")
(java:define-call parse-java-int ("java.lang.Integer" "parseInt")
  :static t :parameters ("java.lang.String") :returns :int)
(java:define-call list-size ("java.util.List" "size") :parameters () :returns :int)
(java:define-call wrong-return ("java.lang.Integer" "parseInt")
  :static t :parameters ("java.lang.String") :returns :long)
(let ((vm (java:start-jvm :classpath (list (namestring (truename "lib/torcl-jvm/build/tests/"))) :options '("-Xcheck:jni" "-Xmx128m"))))
  (check-java "static" 42 (java:static "java.lang.Integer" "parseInt" "42"))
  (check-java "binding" '(10 20) (mapcar #'parse-java-int '("10" "20")))
  (check-java "collection" '("hello" 42)
    (java:with-scope ()
      (let ((items (java:new 'array-list)))
        (java:call items "add" "hello")
        (java:call items "add" 42)
        (java:to-list items))))
  (let ((expired nil) (retained nil))
    (handler-case
        (java:with-scope ()
          (setf expired (java:new 'array-list) retained (java:retain expired))
          (error "leave scope"))
      (error () nil))
    (check-java "scope-expired" :caught
      (handler-case (java:call expired "size") (java:jvm-error () :caught)))
    (check-java "scope-retained" 0 (java:call retained "size"))
    (java:release retained))
  (java:with-scope ()
    (let ((items (java:new 'array-list)))
      (java:call items "add" 10)
      (java:call items "add" 20)
      (check-java "remove-index" 20 (java:call items '("remove" :int) 1))
      (check-java "remove-object" t (java:call items '("remove" "java.lang.Object") 10))))
  (check-java "typed-long" "long" (java:static "ErgonomicFixture" "number" (java:as :long 42)))
  (check-java "int-default" "int" (java:static "ErgonomicFixture" "number" 42))
  (check-java "long-default" "long" (java:static "ErgonomicFixture" "number" 2147483648))
  (check-java "null-ambiguity" :caught
    (handler-case (java:static "ErgonomicFixture" "ambiguous" java:+null+)
      (java:ambiguous-call () :caught)))
  (check-java "typed-null" "string" (java:static "ErgonomicFixture" "ambiguous" (java:as "java.lang.String" java:+null+)))
  (let ((saved nil))
    (java:with-scope ()
      (let ((callback (java:lambda "java.util.function.IntUnaryOperator" (x) (torcl-ext:gc) (1+ x))))
        (setf saved (java:retain callback))))
    (check-java "retained-callback" 42 (java:call saved "applyAsInt" 41))
    (check-java "java-thread" 42 (java:static "JvmFixture" "onThread" saved 41))
    (java:release saved))
  (java:with-scope ()
    (let ((callback (java:lambda "java.util.function.Supplier" () (java:new "java.lang.Object"))))
      (check-java "scoped-callback-return" "java.lang.Object"
        (java:call (java:call (java:call callback "get") "getClass") "getName")))
    (let ((comparator (java:implement "java.util.Comparator"
                        ("compare" (a b) (- (length a) (length b))))))
      (check-java "interface" -2 (java:call comparator "compare" "a" "abc"))))
  (check-java "boxing-specificity" "integer" (java:static "ErgonomicFixture" "boxed" 1))
  (check-java "no-implicit-narrowing" :caught
    (handler-case (java:static "ErgonomicFixture" "narrowed" 1) (java:java-error () :caught)))
  (check-java "explicit-byte" "byte" (java:static "ErgonomicFixture" "narrowed" (java:as :byte 1)))
  (check-java "byte-range" :caught
    (handler-case (java:static "ErgonomicFixture" "narrowed" (java:as :byte 256)) (java:java-error () :caught)))
  (java:with-scope ()
    (let ((strings (java:new-array "java.lang.String" 2)) (object (java:new "ErgonomicFixture")))
      (setf (java:array-ref strings 0) "a" (java:array-ref strings 1) "b")
      (check-java "explicit-varargs-array" "a,b" (java:static "ErgonomicFixture" "join" strings))
      (check-java "field" 3 (java:field object "value"))
      (setf (java:field object "value") 17)
      (check-java "set-field" 17 (java:field object "value"))
      (check-java "final-static-field" 2147483647 (java:static-field "java.lang.Integer" "MAX_VALUE")))
    (let ((items (java:new 'array-list)))
      (java:with-scope () (java:call items "add" "still alive"))
      (check-java "outer-reference" 1 (java:call items "size"))
      (check-java "void" nil (java:call items "clear")))
    (let ((callback (java:lambda "java.util.function.IntUnaryOperator" (x) (+ 2 x))))
      (java:call (java:call callback "andThen" callback) "applyAsInt" 2)
      (check-java "default-interface-method" 6 (java:call (java:call callback "andThen" callback) "applyAsInt" 2)))
    (let* ((callback (java:lambda "java.util.function.Supplier" () (error "callback boom"))))
      (check-java "callback-condition" :caught
        (handler-case (java:call callback "get") (java:java-error () :caught)))))
  (let ((copy nil))
    (java:with-scope ()
      (let* ((callback (java:lambda "java.util.function.IntUnaryOperator" (x) (+ 3 x)))
             (identity (java:static "java.util.Objects" "requireNonNull" callback)))
        (setf copy (java:retain identity))))
    (check-java "callback-return-lease" 7 (java:call copy "applyAsInt" 4))
    (java:release copy))
  (java:with-scope ()
    (let ((objects (java:new-array "java.lang.Object" 1)))
      (setf (java:array-ref objects 0) 1)
      (check-java "array-boxing" "java.lang.Integer" (java:static "ErgonomicFixture" "elementClass" objects)))
    (let ((callback (java:implement "ErgonomicFixture$Overloaded"
                      (("apply" :int) (x) (+ 1 x))
                      (("apply" "java.lang.String") (s) (concatenate 'string s "!")))))
      (check-java "overloaded-int-callback" 8 (java:static "ErgonomicFixture" "intCallback" callback))
      (check-java "overloaded-string-callback" "hello!" (java:static "ErgonomicFixture" "stringCallback" callback)))
    (check-java "missing-callback" :caught
      (handler-case (java:implement "ErgonomicFixture$Overloaded" (("apply" :int) (x) x))
        (java:jvm-error () :caught)))
    (check-java "callback-arity" :caught
      (handler-case (java:lambda "java.util.function.IntUnaryOperator" () 1) (java:jvm-error () :caught)))
    (let ((loader (java:static "JvmFixture" "isolatedLoader")))
      (check-java "class-loader" "int" (java:static (java:find-class "ErgonomicFixture" loader) "number" 1))
      (java:call loader "close")))
  (check-java "verify-binding" t (java:verify 'parse-java-int))
  (check-java "verify-return" :caught
    (handler-case (java:verify 'wrong-return) (java:java-error () :caught)))
  (check-java "named-instance" 0
    (java:with-scope () (list-size (java:new "java.util.ArrayList"))))
  (check-java "member-inspection" t (consp (java:describe-class "java.lang.String")))
  (handler-case (java:static "ErgonomicFixture" "fail") (java:java-error () nil))
  (check-java "invoke-once" 1 (java:static-field "ErgonomicFixture" "attempts"))
  (check-java "resource-primary-error" :primary
    (handler-case
        (java:with-resource (resource (java:new "ErgonomicFixture")) (error "primary error"))
      (java:java-error () :cleanup)
      (error () :primary)))
  (check-java "resource-close-error" :caught
    (handler-case
        (java:with-resource (resource (java:new "ErgonomicFixture")) 42)
      (java:java-error () :caught)))
  (check-java "resource-closed" 2 (java:static-field "ErgonomicFixture" "closes"))
  (check-java "callback-return-boxing" "java.lang.Integer"
    (java:with-scope ()
      (java:static "ErgonomicFixture" "supplierClass" (java:lambda "java.util.function.Supplier" () 42))))
  (check-java "exception-classification" :java-error
    (handler-case (java:static "ErgonomicFixture" "misleadingError")
      (java:ambiguous-call () :incorrect-ambiguity)
      (java:java-error () :java-error)))
  (check-java "covariant-functional-interface" "hello"
    (java:with-scope ()
      (java:static "ErgonomicFixture" "throughWide"
        (java:lambda "ErgonomicFixture$Covariant" () "hello"))))
  (check-java "stop-no-leaks" t (java:stop-jvm vm)))
(format t "JAVA-ERGONOMIC-PASS~%")
