(defparameter *bridge* (egcl-ffi:load-foreign-library
  (concatenate 'string (egcl-ext:getenv "EGCL_JVM_PROBE_DIR") "/libprobe.so")))
(defun bridge (name result types args)
  (egcl-ffi:foreign-call (egcl-ffi:foreign-symbol-pointer name *bridge*) result types args))
(defun check (name expected actual)
  (format t "~A expected=~A actual=~A~%" name expected actual)
  (finish-output)
  (unless (eql expected actual) (error "Probe mismatch: ~A" name)))
(defun java-call (method value)
  (bridge "probe_call" :int '(:int :int) (list method value)))
(check "START" 0 (bridge "probe_start" :int nil nil))
(format t "HOTSPOT-HANDLER-PRESERVED=~D~%" (bridge "probe_handler_preserved" :int nil nil))
(finish-output)
(format t "LISP-STACK-CONTEXT=~D (bit0=pthread-stack bit1=alt-stack)~%"
  (bridge "probe_thread_context" :int nil nil))
(check "TWICE" 42 (java-call 0 21))
(check "JAVA-GC" 19 (java-call 3 0))
(check "JAVA-NULL" 29 (java-call 5 0))
(check "JAVA-OVERFLOW" 23 (java-call 4 0))
(check "JAVA-EXCEPTION" -200 (java-call 6 0))
(check "AFTER-EXCEPTION" 42 (java-call 0 21))
(defparameter *callback* (egcl-ffi:make-callback
  (lambda (depth)
    (egcl-ext:gc)
    (check "CALLBACK-JAVA-GC" 19 (java-call 3 0))
    (java-call 1 depth)) :int '(:int)))
(bridge "probe_set_callback" :void '(:pointer)
        (list (egcl-ffi:callback-pointer *callback*)))
(check "NESTED" 15 (java-call 1 8))
(check "JAVA-THREAD" 11 (java-call 2 4))
(check "OVERLAPPING-COLLECTORS" 11 (java-call 8 4))
(bridge "probe_set_callback" :void '(:pointer) (list (egcl-ffi:null-pointer)))
(egcl-ffi:free-callback *callback*)
(let ((failing (egcl-ffi:make-callback
                 (lambda (n) (declare (ignore n)) (error "probe-callback-error"))
                 :int '(:int))))
  (bridge "probe_set_callback" :void '(:pointer)
          (list (egcl-ffi:callback-pointer failing)))
  (check "LISP-EXCEPTION-CONTAINED" :caught
    (handler-case (java-call 1 1)
      (egcl-ffi:ffi-error () :caught)))
  ;; Clear the recorded same-thread diagnostic before checking the other path.
  (egcl-ffi:callback-error failing)
  (check "FOREIGN-THREAD-ERROR-RESULT" 0 (java-call 2 1))
  (check "FOREIGN-THREAD-ERROR-RECORDED" t
    (not (null (search "probe-callback-error" (egcl-ffi:callback-error failing)))))
  (check "FOREIGN-THREAD-ERROR-CONSUMED" nil (egcl-ffi:callback-error failing))
  (bridge "probe_set_callback" :void '(:pointer) (list (egcl-ffi:null-pointer)))
  (egcl-ffi:free-callback failing))
(check "HANDLES" 10000 (bridge "probe_handles" :int '(:int) '(10000)))
(let ((worker (egcl-thread:make-thread (lambda () (java-call 7 3000)))))
  (loop repeat 1000
        until (= 1 (bridge "probe_active" :int nil nil))
        do (sleep 0.001))
  (check "JAVA-CALL-ACTIVE" 1 (bridge "probe_active" :int nil nil))
  (egcl-ext:gc)
  (check "GC-FINISHED-WHILE-JAVA-ACTIVE" 1 (bridge "probe_active" :int nil nil))
  (multiple-value-bind (value completed) (egcl-thread:join-thread worker :timeout 10)
    (check "JAVA-CALL-JOINED" t completed)
    (check "JAVA-CALL-RESULT" 31 value)))
(format t "CACHED-JNI-NS=~F~%" (bridge "probe_cached_ns" :double '(:int) '(1000000)))
(finish-output)
(check "SHUTDOWN" 0 (bridge "probe_stop" :int nil nil))
(format t "PROBE-COMPLETE~%")
