FROM registry.fedoraproject.org/fedora:44

# systemd supplies the same per-command memory limits as local packaging.
RUN dnf -y install systemd dbus-daemon dnf5-plugins \
        gcc gcc-c++ clang binutils rpm-build rpm cpio python3 curl unzip git \
        qemu-user wine mingw64-gcc mingw64-binutils glibc make java-devel \
        mkdocs mkdocs-material procps-ng findutils \
    && dnf clean all
WORKDIR /workspace
CMD ["/sbin/init"]
