;;; SPDX-FileCopyrightText: Copyright (C) 2026 Anthony Green <green@moxielogic.com>
;;; SPDX-License-Identifier: GPL-3.0-or-later WITH Classpath-exception-2.0

;;; Public stackful fibers, separate from OS-backed EGCL-THREAD objects.
(in-package "EGCL-FIBER")
(export '(fiber fiber-p make-fiber current-fiber list-all-fibers
          fiber-name fiber-state fiber-alive-p fiber-carrier-thread
          fiber-result fiber-error-p fiber-yield fiber-sleep fiber-join fiber-park
          fiber-pin fiber-unpin fiber-can-yield-p with-fiber-pinned *pinned-blocking-action*
          scheduler-group scheduler-group-p scheduler-group-carriers
          start-fibers submit-fiber finish-fibers run-fibers fiber-group-done-p
          fiber-error fiber-error-fiber fiber-error-cause
          fiber-still-running print-fiber-backtrace))

(define-condition fiber-error (error)
  ((fiber :initarg :fiber :reader fiber-error-fiber)
   (cause :initarg :cause :reader fiber-error-cause)))

(define-condition fiber-still-running (error) ())

(defstruct (fiber (:constructor %make-fiber))
  id name epoch group packet carrier
  (lock (egcl-thread:make-mutex)))

(defstruct (scheduler-group (:constructor %make-group))
  id epoch carrier-list fibers closed finished results failure idle-error
  (finish-lock (egcl-thread:make-mutex))
  (lock (egcl-thread:make-mutex)))

(defun %check-fiber (fiber)
  (unless (fiber-p fiber)
    (error 'type-error :datum fiber :expected-type 'fiber))
  (unless (eql (fiber-epoch fiber) (egcl::%native-fiber :epoch))
    (error "Fiber belongs to an earlier runtime session"))
  fiber)

(defun %check-group (group)
  (unless (scheduler-group-p group)
    (error 'type-error :datum group :expected-type 'scheduler-group))
  (unless (eql (scheduler-group-epoch group) (egcl::%native-fiber :epoch))
    (error "Scheduler group belongs to an earlier runtime session"))
  group)

(defun %seconds (seconds)
  (unless (or (null seconds) (and (realp seconds) (not (minusp seconds))))
    (error 'type-error :datum seconds :expected-type '(or null (real 0))))
  (egcl::%native-fiber :seconds (and seconds (float seconds 1d0))))

(defun make-fiber (function &key name arguments stack-size initial-bindings)
  "Create an unscheduled fiber. INITIAL-BINDINGS is an alist of special values."
  (unless (or (functionp function) (and (symbolp function) (fboundp function)))
    (error 'type-error :datum function :expected-type '(or function symbol)))
  (unless (or (null name) (stringp name))
    (error 'type-error :datum name :expected-type '(or null string)))
  (unless (or (null stack-size) (and (integerp stack-size) (<= 524288 stack-size 1073741824)))
    (error 'type-error :datum stack-size :expected-type '(or null (integer 524288 1073741824))))
  (let* ((bindings (append
                    (list (cons '*package* *package*)
                          (cons '*standard-input* *standard-input*)
                          (cons '*standard-output* *standard-output*)
                          (cons '*error-output* *error-output*)
                          (cons '*trace-output* *trace-output*)
                          (cons '*debug-io* *debug-io*)
                          (cons '*query-io* *query-io*)
                          (cons '*terminal-io* *terminal-io*))
                    initial-bindings))
         (entry (lambda ()
                  (handler-case
                      (cons t (multiple-value-list
                                (progv (mapcar #'car bindings) (mapcar #'cdr bindings)
                                  (apply function arguments))))
                    (error (condition) (cons nil condition)))))
         (fiber (%make-fiber :name name :epoch (egcl::%native-fiber :epoch))))
    (setf (fiber-id fiber) (egcl::%native-fiber :make entry (or stack-size 524288)))
    (egcl::%native-fiber :register (fiber-id fiber) fiber)))

(defun current-fiber () (egcl::%native-fiber :current))
(defun list-all-fibers () (coerce (egcl::%native-fiber :all) 'list))
(defun fiber-state (fiber)
  (%check-fiber fiber)
  (aref #(:created :runnable :running :suspended :suspended :running :suspended :dead)
        (egcl::%native-fiber :state (fiber-id fiber))))
(defun print-fiber-backtrace (fiber &key (stream *standard-output*) (count 20))
  (%check-fiber fiber)
  (unless (and (integerp count) (>= count 0))
    (error 'type-error :datum count :expected-type '(integer 0)))
  (let ((frames (egcl::%native-fiber :backtrace (fiber-id fiber) count)))
    (unless frames (error 'fiber-still-running))
    (format stream "Fiber ~A (~A)~%" (or (fiber-name fiber) "<unnamed>") (fiber-state fiber))
    (loop for frame across frames for n from 0 do (format stream "  ~D: ~A~%" n frame)))
  (values))
(defun fiber-alive-p (fiber) (not (eq :dead (fiber-state fiber))))
(defun fiber-carrier-thread (fiber)
  (%check-fiber fiber)
  (or (egcl::%native-fiber :carrier (fiber-id fiber)) (fiber-carrier fiber)))
(defun fiber-yield () (egcl::%native-fiber :yield))
(defun fiber-sleep (seconds)
  (unless seconds (error 'type-error :datum seconds :expected-type '(real 0)))
  (egcl::%native-fiber :sleep (%seconds seconds)))

(defvar *pinned-blocking-action* :warn)
(defun fiber-pin (&optional (fiber (current-fiber)))
  (%check-fiber fiber)
  (egcl::%native-fiber :pin (fiber-id fiber)))
(defun fiber-unpin (&optional (fiber (current-fiber)))
  (%check-fiber fiber)
  (egcl::%native-fiber :unpin (fiber-id fiber)))
(defun fiber-can-yield-p (&optional (fiber (current-fiber)))
  (%check-fiber fiber)
  (egcl::%native-fiber :can-yield (fiber-id fiber)))
(defmacro with-fiber-pinned ((&optional (fiber '(current-fiber))) &body body)
  (let ((saved (gensym "FIBER")))
    `(let ((,saved ,fiber))
       (fiber-pin ,saved)
       (unwind-protect (progn ,@body) (fiber-unpin ,saved)))))
(defun fiber-park (predicate &key timeout)
  (let ((deadline (and timeout (+ (get-internal-real-time)
                                 (* (%seconds timeout) internal-time-units-per-second)))))
    (loop
      (when (funcall predicate) (return t))
      (let ((left (and deadline (/ (- deadline (get-internal-real-time))
                                  internal-time-units-per-second))))
        (when (and left (<= left 0)) (return nil))
        (fiber-sleep (if left (min left 0.001d0) 0.001d0))))))

(defun %await (fiber timeout)
  (%check-fiber fiber)
  (when (eq fiber (current-fiber)) (return-from %await nil))
  (let* ((seconds (%seconds timeout))
         (deadline (and seconds (+ (get-internal-real-time)
                                   (* seconds internal-time-units-per-second)))))
    (egcl-thread:with-mutex ((fiber-lock fiber) :timeout seconds)
      (or (fiber-packet fiber)
          (let ((remaining (and deadline
                             (max 0d0 (/ (- deadline (get-internal-real-time))
                                         internal-time-units-per-second)))))
            (when (egcl::%native-fiber :wait (fiber-id fiber) remaining)
              (setf (fiber-carrier fiber) (fiber-carrier-thread fiber))
              (setf (fiber-packet fiber) (egcl::%native-fiber :join (fiber-id fiber)))))))))

(defun fiber-join (fiber &key timeout)
  ;; Check before acquiring the join lock: another execution may already hold
  ;; that lock while waiting for this very fiber to finish.
  (when (eq fiber (current-fiber)) (error "A fiber cannot join itself"))
  (let ((packet (%await fiber timeout)))
    (cond ((null packet) (values nil nil))
          ((car packet) (values-list (cdr packet)))
          (t (error 'fiber-error :fiber fiber :cause (cdr packet))))))
(defun fiber-result (fiber)
  (let ((packet (%await fiber 0))) (and packet (car packet) (cdr packet))))
(defun fiber-error-p (fiber)
  (let ((packet (%await fiber 0))) (and packet (not (car packet)))))

(defun scheduler-group-carriers (group)
  (%check-group group)
  (copy-list (scheduler-group-carrier-list group)))

(defun start-fibers (fibers &key (carrier-count (egcl::%native-fiber :processors)) idle-hook)
  (when idle-hook
    (unless (or (functionp idle-hook) (and (symbolp idle-hook) (fboundp idle-hook)))
      (error 'type-error :datum idle-hook :expected-type '(or function symbol))))
  (dolist (fiber fibers)
    (%check-fiber fiber)
    (unless (eq :created (fiber-state fiber)) (error "Fiber is already scheduled")))
  (unless (and (integerp carrier-count) (> carrier-count 0))
    (error 'type-error :datum carrier-count :expected-type '(integer 1)))
  (let ((group (%make-group :epoch (egcl::%native-fiber :epoch)
                            :id (egcl::%native-fiber :start carrier-count))))
    (setf (scheduler-group-carrier-list group)
          (coerce (egcl::%native-fiber :carriers (scheduler-group-id group)) 'list))
    (handler-case
        (progn
          (when idle-hook
            (egcl::%native-fiber :idle-hook (scheduler-group-id group)
              (lambda ()
                (unless (egcl-thread:with-mutex ((scheduler-group-lock group))
                          (scheduler-group-idle-error group))
                  (handler-case (funcall idle-hook group)
                    (error (condition)
                      (egcl-thread:with-mutex ((scheduler-group-lock group))
                        (unless (scheduler-group-idle-error group)
                          (setf (scheduler-group-idle-error group) condition)))))))))
          (dolist (fiber fibers) (submit-fiber group fiber))
          group)
      (error (condition)
        (ignore-errors (finish-fibers group))
        (error condition)))))

(defun submit-fiber (group fiber)
  (%check-group group)
  (%check-fiber fiber)
  (egcl-thread:with-mutex ((scheduler-group-lock group))
    (when (scheduler-group-closed group) (error "Scheduler group is closed"))
    (egcl-thread:with-mutex ((fiber-lock fiber))
      (when (fiber-group fiber) (error "Fiber already belongs to a scheduler group"))
      (setf (fiber-group fiber) group)
      (handler-case
          (egcl::%native-fiber :submit (scheduler-group-id group) (fiber-id fiber))
        (error (condition) (setf (fiber-group fiber) nil) (error condition)))
      (setf (scheduler-group-fibers group)
            (append (scheduler-group-fibers group) (list fiber)))))
  fiber)

(defun fiber-group-done-p (group)
  (%check-group group)
  (egcl-thread:with-mutex ((scheduler-group-lock group))
    (every (lambda (fiber) (not (fiber-alive-p fiber))) (scheduler-group-fibers group))))

(defun finish-fibers (group)
  (%check-group group)
  (when (or (and (current-fiber) (eq group (fiber-group (current-fiber))))
            (member (egcl-thread:current-thread) (scheduler-group-carrier-list group)))
    (error "An execution cannot finish its own scheduler group"))
  (egcl-thread:with-mutex ((scheduler-group-finish-lock group))
    (unless (scheduler-group-finished group)
      (egcl-thread:with-mutex ((scheduler-group-lock group))
        (setf (scheduler-group-closed group) t))
      (let ((results nil) (failure nil))
        (dolist (fiber (scheduler-group-fibers group))
          (let ((packet (%await fiber nil)))
            (push (and (car packet) (cadr packet)) results)
            (unless (car packet) (unless failure (setq failure fiber)))))
        (egcl::%native-fiber :shutdown (scheduler-group-id group))
        (setf (scheduler-group-results group) (nreverse results))
        (setf (scheduler-group-failure group) failure)
        (setf (scheduler-group-finished group) t)))
    (when (scheduler-group-idle-error group) (error (scheduler-group-idle-error group)))
    (if (scheduler-group-failure group)
        (let ((fiber (scheduler-group-failure group)))
          (error 'fiber-error :fiber fiber :cause (cdr (fiber-packet fiber))))
        (copy-list (scheduler-group-results group)))))

(defun run-fibers (fibers &key (carrier-count (egcl::%native-fiber :processors)) idle-hook)
  (finish-fibers (start-fibers fibers :carrier-count carrier-count :idle-hook idle-hook)))
(in-package "COMMON-LISP-USER")
