;;; SPDX-FileCopyrightText: Copyright (C) 2026 Anthony Green <green@moxielogic.com>
;;; SPDX-License-Identifier: GPL-3.0-or-later WITH Classpath-exception-2.0

;;;; LOOP expansion into ordinary lexical bindings and control flow.
;;;; Drivers emit their tests and assignments in source order. A shared first
;;;; iteration flag lets each driver step at its own position on subsequent
;;;; passes, including the pass on which a later driver terminates.

(in-package "COMMON-LISP")

(defun egcl::%loop-key (object)
  (and (symbolp object) (string-upcase (symbol-name object))))

(defun egcl::%expand-loop (clauses)
  (let ((top (gensym "LOOP-TOP")) (end (gensym "LOOP-END")))
    (if (or (null clauses) (consp (car clauses)))
        `(block nil (tagbody ,top ,@clauses (go ,top)))
        (let ((remaining clauses) (bindings nil) (body nil)
              (initially nil) (finally nil) (block-name nil)
              (first (gensym "LOOP-FIRST")) (accumulators nil)
              (result nil) (boolean-result-p nil)
              (wrappers nil) (pending nil) (checks nil) (parallel nil) (it nil))
          (labels
              ((take ()
                 (unless remaining (error "Missing operand in LOOP: ~S" clauses))
                 (pop remaining))
               (key () (and remaining (egcl::%loop-key (car remaining))))
               (at (name) (equal (key) name))
               (value ()
                 (let ((form (take)))
                   (if (and it (equal (egcl::%loop-key form) "IT")) it form)))
               (bind (var value)
                 (when (assoc var bindings) (error 'program-error))
                 (push (list var value) bindings)
                 var)
               (emit (form) (push form body))
               (read-type ()
                 (cond ((at "OF-TYPE") (take) (take))
                       ((member (key) '("FIXNUM" "FLOAT" "T" "NIL") :test #'equal) (take))
                       (t t)))
               (default-value (type)
                 (cond ((subtypep type 'float) (coerce 0 type))
                       ((subtypep type 'number) 0)
                       ((subtypep type 'character) #\Space)
                       (t nil)))
               (default-pattern (pattern type)
                 (cond ((null pattern) nil)
                       ((symbolp pattern) (default-value type))
                       ((consp pattern)
                        (cons (default-pattern (car pattern) (if (consp type) (car type) type))
                              (default-pattern (cdr pattern) (if (consp type) (cdr type) type))))
                       (t (error "Invalid LOOP variable pattern ~S" pattern))))
               (bind-initial-pattern (pattern value)
                 (cond ((null pattern) nil)
                       ((symbolp pattern) (bind pattern value))
                       ((consp pattern)
                        (bind-initial-pattern (car pattern) `(car ,value))
                        (bind-initial-pattern (cdr pattern) `(cdr ,value)))
                       (t (error "Invalid LOOP variable pattern ~S" pattern))))
               (bind-pattern (pattern type)
                 (cond ((null pattern) nil)
                       ((symbolp pattern) (bind pattern (default-value type)))
                       ((consp pattern)
                        (bind-pattern (car pattern) (if (consp type) (car type) type))
                        (bind-pattern (cdr pattern) (if (consp type) (cdr type) type)))
                       (t (error "Invalid LOOP variable pattern ~S" pattern))))
               (assign (var value)
                 (if parallel
                     (let ((next (bind (gensym "LOOP-NEXT") nil)))
                       (push `(setq ,var ,next) pending)
                       (emit `(setq ,next ,value))
                       next)
                     (progn (emit `(setq ,var ,value)) var)))
               (assign-pattern (pattern value)
                 (cond ((null pattern) nil)
                       ((symbolp pattern) (assign pattern value))
                       (t (let ((whole (bind (gensym "LOOP-DESTRUCTURE") nil)))
                            (emit `(setq ,whole ,value))
                            (assign-pattern (car pattern) `(car ,whole))
                            (assign-pattern (cdr pattern) `(cdr ,whole))))))
               (forms ()
                 (let ((out nil))
                   (do () ((not (consp (car remaining))) (nreverse out))
                     (push (take) out))))
               (accumulate (kind value)
                 (let* ((named (when (at "INTO") (take) (take)))
                        (name (or named :implicit))
                        (entry (assoc name accumulators))
                        (family (cond ((member kind '("COLLECT" "APPEND" "NCONC") :test #'equal) :list)
                                      ((member kind '("SUM" "COUNT") :test #'equal) :sum)
                                      (t :extremum)))
                        (type (read-type)))
                   (when (and (not named) boolean-result-p)
                     (error 'program-error))
                   (unless entry
                     (let ((var (or named (gensym "LOOP-RESULT")))
                           (aux (gensym "LOOP-ACC")))
                       (bind var (if (eq family :sum)
                                     (if (subtypep type 'float) (coerce 0 type) 0)
                                     nil))
                       (bind aux (if (eq family :list) '(list nil) nil))
                       ;; A list collector keeps its tail separately from the
                       ;; visible result, so references to that result stay live.
                       (let ((tail (when (eq family :list)
                                     (bind (gensym "LOOP-TAIL") aux))))
                         (setq entry (list name family var aux tail))
                         (push entry accumulators))
                       (unless named (setq result var))))
                   (unless (eq family (second entry))
                     (error "Incompatible LOOP accumulation for ~S" name))
                   (let ((var (third entry)) (aux (fourth entry)) (tail (fifth entry)))
                     (cond
                       ((eq family :list)
                        (let ((part (gensym "LOOP-PART")))
                          `(let ((,part ,(cond ((equal kind "COLLECT") `(list ,value))
                                              ((equal kind "APPEND") `(copy-list ,value))
                                              (t value))))
                             (when ,part
                               (rplacd ,tail ,part)
                               (setq ,tail (last ,part) ,var (cdr ,aux))))))
                       ((equal kind "COUNT") `(when ,value (incf ,var)))
                       ((equal kind "SUM") `(incf ,var ,value))
                       (t (let ((next (gensym "LOOP-VALUE")))
                            `(let ((,next ,value))
                               (if ,aux
                                   (setq ,var (,(if (equal kind "MAXIMIZE") 'max 'min) ,var ,next))
                                   (setq ,var ,next ,aux t)))))))))
               (action ()
                 (let ((clause (egcl::%loop-key (take))))
                   (cond
                     ((member clause '("DO" "DOING") :test #'equal)
                      `(progn ,@(forms)))
                     ((equal clause "RETURN") `(return-from ,block-name ,(value)))
                     ((member clause '("WHEN" "IF" "UNLESS") :test #'equal)
                      (let ((test (value)) (yes nil) (no nil)
                            (saved-it it) (test-value (gensym "LOOP-CONDITION")))
                        (setq it test-value)
                        (push (action) yes)
                        (setq it nil)
                        (do () ((not (at "AND"))) (take) (push (action) yes))
                        (when (at "ELSE")
                          (take) (push (action) no)
                          (do () ((not (at "AND"))) (take) (push (action) no)))
                        (when (at "END") (take))
                        (setq it saved-it)
                        `(let ((,test-value ,test))
                           (if ,(if (equal clause "UNLESS") `(not ,test-value) test-value)
                               (progn ,@(nreverse yes)) (progn ,@(nreverse no))))))
                     ((member clause '("COLLECT" "COLLECTING" "APPEND" "APPENDING"
                                        "NCONC" "NCONCING" "SUM" "SUMMING" "COUNT" "COUNTING"
                                        "MAXIMIZE" "MAXIMIZING" "MINIMIZE" "MINIMIZING") :test #'equal)
                      (let ((canonical (or (cdr (assoc clause
                                                     '(("COLLECTING" . "COLLECT") ("APPENDING" . "APPEND")
                                                       ("NCONCING" . "NCONC") ("SUMMING" . "SUM")
                                                       ("COUNTING" . "COUNT") ("MAXIMIZING" . "MAXIMIZE")
                                                       ("MINIMIZING" . "MINIMIZE")) :test #'equal)) clause)))
                        (accumulate canonical (value))))
                     ((member clause '("ALWAYS" "NEVER" "THEREIS") :test #'equal)
                      (when (assoc :implicit accumulators) (error 'program-error))
                      (setq boolean-result-p t)
                      (let ((value (take)))
                        (if (equal clause "THEREIS")
                            (let ((temp (gensym "LOOP-TEST")))
                              `(let ((,temp ,value)) (when ,temp (return-from ,block-name ,temp))))
                            (progn (setq result t)
                                   `(when ,(if (equal clause "ALWAYS") `(not ,value) value)
                                      (return-from ,block-name nil))))))
                     (t (error "Unsupported LOOP action ~S" clause)))))
               (driver ()
                 (let* ((var (take)) (type (read-type)) (mode (egcl::%loop-key (take))))
                   (cond
                     ((equal mode "BEING")
                      (when (member (key) '("EACH" "THE") :test #'equal) (take))
                      (let* ((path (egcl::%loop-key (take)))
                             (keys (member path '("HASH-KEY" "HASH-KEYS") :test #'equal))
                             (hashp (or keys (member path '("HASH-VALUE" "HASH-VALUES") :test #'equal)))
                             (statuses (cond
                                         ((member path '("SYMBOL" "SYMBOLS") :test #'equal)
                                          '(:internal :external :inherited))
                                         ((member path '("PRESENT-SYMBOL" "PRESENT-SYMBOLS") :test #'equal)
                                          '(:internal :external))
                                         ((member path '("EXTERNAL-SYMBOL" "EXTERNAL-SYMBOLS") :test #'equal)
                                          '(:external))))
                             (iterator (gensym "LOOP-NEXT-ENTRY"))
                             (present (gensym "LOOP-PRESENT"))
                             (key-var (gensym "LOOP-KEY"))
                             (value-var (gensym "LOOP-VALUE"))
                             (other nil))
                        (unless (or hashp statuses)
                          (error "Unsupported LOOP iteration path ~S" path))
                        (let ((domain
                                (cond ((member (key) '("OF" "IN") :test #'equal)
                                       (take) (take))
                                      (statuses '*package*)
                                      (t (error "Missing hash table in LOOP")))))
                          (let ((container (bind (gensym "LOOP-CONTAINER") domain)))
                            (push (if hashp
                                      `(with-hash-table-iterator (,iterator ,container))
                                      `(with-package-iterator (,iterator (list ,container) ,@statuses)))
                                  wrappers)))
                        (when (at "USING")
                          (take)
                          (let ((using (take)))
                            (unless (and hashp (consp using) (consp (cdr using)) (null (cddr using))
                                         (equal (egcl::%loop-key (car using))
                                                (if keys "HASH-VALUE" "HASH-KEY")))
                              (error "Invalid LOOP hash USING clause: ~S" using))
                            (setq other (cadr using))
                            (bind-pattern other t)))
                        (bind-pattern var type)
                        ;; Iterator values are lexical to this call; calculate
                        ;; staged assignments inside their MULTIPLE-VALUE-BIND.
                        (let ((outer-body body))
                          (setq body nil)
                          (assign-pattern var (if (or keys statuses) key-var value-var))
                          (when other (assign-pattern other (if keys value-var key-var)))
                          (let ((stores (nreverse body)))
                            (setq body outer-body)
                            (emit `(multiple-value-bind (,present ,key-var ,value-var) (,iterator)
                                     (unless ,present (go ,end))
                                     ,@stores))))))
                     ((member mode '("IN" "ON" "ACROSS") :test #'equal)
                      (let* ((sequence (bind (gensym "LOOP-SEQUENCE") (take)))
                             (index (gensym "LOOP-INDEX")) (step ''cdr)
                             ;; ON over a plain variable tracks the cursor
                             ;; itself: the variable starts at the whole list,
                             ;; so INITIALLY sees it, and it holds the
                             ;; terminating atom once the list is exhausted, so
                             ;; FINALLY sees that. A destructuring pattern
                             ;; instead keeps the parts of the last real cons —
                             ;; the terminating atom is never destructured.
                             (cursor-var (and (equal mode "ON") var (symbolp var) var)))
                        (when (at "BY")
                          (take)
                          (setq step (bind (gensym "LOOP-LIST-STEP") (take))))
                        (if cursor-var
                            (bind cursor-var sequence)
                            (bind-pattern var type))
                        (if (equal mode "ACROSS")
                            (progn
                              (bind index 0)
                              (emit `(unless ,first (incf ,index)))
                              (emit `(when (>= ,index (length ,sequence)) (go ,end)))
                              (assign-pattern var `(aref ,sequence ,index)))
                            (progn
                              (emit `(unless ,first (setq ,sequence (funcall ,step ,sequence))))
                              (emit `(when (,(if (equal mode "ON") 'atom 'endp) ,sequence)
                                       ,@(when cursor-var `((setq ,cursor-var ,sequence)))
                                       (go ,end)))
                              (assign-pattern var (if (equal mode "IN") `(car ,sequence) sequence))))))
                     ((equal mode "=")
                      (let* ((init (take)) (step init))
                        (when (at "THEN") (take) (setq step (take)))
                        (bind-pattern var type)
                        (assign-pattern var `(if ,first ,init ,step))))
                     ((member mode '("FROM" "UPFROM" "DOWNFROM" "BELOW" "ABOVE" "TO" "UPTO" "DOWNTO" "BY") :test #'equal)
                      ;; NIL suppresses the user binding, but arithmetic
                      ;; iteration still needs a private counter.
                      (unless var (setq var (gensym "LOOP-COUNTER")))
                      (let ((start 0) (bound nil) (boundary nil) (stride 1)
                            (down nil))
                        (push (intern mode :keyword) remaining)
                        ;; Bind each supplied form as it is encountered:
                        ;; arithmetic options can appear in any order.
                        (do () ((not (member (key) '("FROM" "UPFROM" "DOWNFROM" "BELOW" "ABOVE" "TO" "UPTO" "DOWNTO" "BY") :test #'equal)))
                          (let* ((option (egcl::%loop-key (take)))
                                 (value (bind (gensym "LOOP-OPTION") (take))))
                            (cond
                              ((member option '("FROM" "UPFROM" "DOWNFROM") :test #'equal)
                               (setq start value)
                               (when (equal option "DOWNFROM") (setq down t)))
                              ((equal option "BY") (setq stride value))
                              (t
                               (setq bound value boundary option)
                               (when (member option '("ABOVE" "DOWNTO") :test #'equal)
                                 (setq down t))))))
                        (bind var start)
                        (assign var `(if ,first ,var (,(if down '- '+) ,var ,stride)))
                        (when boundary
                          (let ((comparison (cond ((equal boundary "BELOW") '>=)
                                                  ((equal boundary "ABOVE") '<=)
                                                  (down '<) (t '>))))
                            (push `(when (,comparison ,var ,bound) (go ,end)) checks)))))
                     (t (error "Unsupported LOOP driver ~S" mode))))))
            (do () ((null remaining))
              (cond
                ((at "NAMED") (take) (setq block-name (take)))
                ((member (key) '("FOR" "AS") :test #'equal)
                 (take)
                 ;; Buffer user-variable stores until the whole group has
                 ;; computed its next values. Driver-private state stays local.
                 (setq parallel t pending nil checks nil)
                 (driver)
                 (do () ((not (at "AND"))) (take) (driver))
                 (setq parallel nil)
                 (do ((stores (nreverse pending) (cdr stores))) ((null stores))
                   (emit (car stores)))
                 (do ((tests (nreverse checks) (cdr tests))) ((null tests))
                   (emit (car tests)))
                 (setq pending nil checks nil))
                ((at "WITH")
                 (take)
                 (let ((group nil))
                   (do ((more t)) ((not more))
                     (let* ((var (take)) (type (read-type))
                            (value (if (at "=") (progn (take) (take)) `(quote ,(default-pattern var type))))
                            (temp (bind (gensym "LOOP-WITH") value)))
                       (push (list var temp) group))
                     (if (at "AND") (take) (setq more nil)))
                   (do ((vars (nreverse group) (cdr vars))) ((null vars))
                     (bind-initial-pattern (caar vars) (cadar vars)))))
                ((at "REPEAT")
                 (take)
                 (let ((count (bind (gensym "LOOP-COUNT") (take))))
                   (emit `(when (<= ,count 0) (go ,end)))
                   (emit `(decf ,count))))
                ((member (key) '("WHILE" "UNTIL") :test #'equal)
                 (let ((whilep (at "WHILE")))
                   (take)
                   (let ((test (take))) (emit `(when ,(if whilep `(not ,test) test) (go ,end))))))
                ((at "INITIALLY") (take) (setq initially (append initially (forms))))
                ((at "FINALLY") (take) (setq finally (append finally (forms))))
                (t (emit (action)))))
            (let ((execution
                    `(macrolet ((loop-finish () '(go ,end)))
                       ,@initially
                       (tagbody ,top ,@(nreverse body) (setq ,first nil) (go ,top) ,end)
                       ,@finally
                       ,result)))
              (do ((tail wrappers (cdr tail))) ((null tail))
                (setq execution (append (car tail) (list execution))))
              `(block ,block-name
                 (let* ((,first t) ,@(nreverse bindings)) ,execution))))))))

(defmacro loop (&rest clauses)
  (egcl::%expand-loop clauses))
