;;;; SPDX-FileCopyrightText: Copyright (C) 2026 Anthony Green <green@moxielogic.com>
;;;; SPDX-License-Identifier: GPL-3.0-or-later WITH Classpath-exception-2.0

(defpackage :egcl-pprint (:use :common-lisp))
(in-package :egcl-pprint)

;; Output is queued as nested blocks so a child's line breaks can be chosen
;; with the enclosing block's actual column, rather than its speculative one.
(defclass %pretty-stream (egcl-gray-streams:fundamental-character-output-stream)
  ((frames :initform nil :accessor %pp-frames)
   (column :initform 0 :accessor %pp-column)))

(defun %pp-enqueue (stream event)
  (push event (car (%pp-frames stream))))

(defmethod egcl-gray-streams:stream-write-char ((stream %pretty-stream) character)
  (%pp-enqueue stream character)
  (setf (%pp-column stream) (if (char= character #\Newline) 0 (1+ (%pp-column stream))))
  character)

(defmethod egcl-gray-streams:stream-line-column ((stream %pretty-stream))
  (%pp-column stream))

(defvar *pp-destination* nil)
(defvar *pp-column* 0)
(defvar *pp-spaces* 0)
(defvar *pp-prefixes* nil)
(defvar *pp-suffixes* nil)
(defvar *pp-lines* 0)
(defvar *pp-stop* nil)

(defun %pp-flush-spaces ()
  (dotimes (i *pp-spaces*) (write-char #\Space *pp-destination*))
  (setf *pp-spaces* 0))

(defun %pp-character (character)
  (incf *pp-column*)
  (if (char= character #\Space)
      (incf *pp-spaces*)
      (progn (%pp-flush-spaces) (write-char character *pp-destination*))))

(defun %pp-text (text)
  (loop for character across text do
    (if (char= character #\Newline)
        (%pp-newline 0 nil nil)
        (%pp-character character))))

(defun %pp-newline (indent trim &optional (repeat-prefixes t))
  (if trim (setf *pp-spaces* 0) (%pp-flush-spaces))
  (when (and *print-lines* (not *print-readably*) (>= (1+ *pp-lines*) *print-lines*))
    (%pp-text " ..")
    (let ((*print-lines* nil))
      (dolist (suffix *pp-suffixes*) (%pp-text suffix)))
    (%pp-flush-spaces)
    (throw *pp-stop* nil))
  (terpri *pp-destination*)
  (incf *pp-lines*)
  (setf *pp-column* 0)
  (when repeat-prefixes
    (dolist (prefix (reverse *pp-prefixes*))
      (loop while (< *pp-column* (car prefix)) do (%pp-character #\Space))
      (%pp-text (cdr prefix))))
  (loop while (< *pp-column* indent) do (%pp-character #\Space)))

(defun %pp-flat-width (events &optional section)
  (let ((width 0))
    (dolist (event events width)
      (cond ((characterp event)
             (when (char= event #\Newline) (return most-positive-fixnum))
             (incf width))
            ((eq (first event) :block)
             (when (or (find #\Newline (second event))
                       (find #\Newline (fourth event)))
               (return most-positive-fixnum))
             (incf width (+ (length (second event)) (length (fourth event))
                            (%pp-flat-width (fifth event)))))
            ((eq (first event) :newline)
             (when section (return width))
             (when (eq (second event) :mandatory) (return most-positive-fixnum)))))))

(defun %pp-render-block (node)
  (let* ((prefix (second node)) (per-line (third node))
         (suffix (fourth node)) (events (fifth node))
         (start *pp-column*)
         (*pp-prefixes* (if per-line (cons (cons start prefix) *pp-prefixes*) *pp-prefixes*))
         (*pp-suffixes* (cons suffix *pp-suffixes*)))
    (%pp-text prefix)
    (let* ((base *pp-column*) (indent base) (section-line *pp-lines*)
           (margin (or *print-right-margin* 80))
           (miser (and *print-miser-width* (<= (- margin base) *print-miser-width*)))
           (linear (> (+ base (%pp-flat-width events) (length suffix)) margin)))
      (loop for remaining on events for event = (car remaining) do
        (cond ((characterp event)
               (if (char= event #\Newline)
                   (%pp-newline 0 nil)
                   (%pp-character event)))
              ((eq (first event) :block) (%pp-render-block event))
              ((eq (first event) :indent)
               (unless miser
                 (setf indent (max 0 (+ (if (eq (second event) :block) base *pp-column*)
                                         (third event))))))
              ((eq (first event) :newline)
               (when (case (second event)
                       (:mandatory t)
                       (:linear linear)
                       (:miser (and miser linear))
                       (:fill (or (> *pp-lines* section-line)
                                  (if miser linear
                                  (> (+ *pp-column* (%pp-flat-width (cdr remaining) t)
                                        (if (find :newline (cdr remaining) :key
                                                  (lambda (x) (and (consp x) (first x))))
                                            0 (length suffix)))
                                     margin)))))
                 (%pp-newline indent t))
               (setf section-line *pp-lines*))))
      (let ((*print-lines* nil)) (%pp-text suffix)))))

(defun %pp-render (node destination)
  (let ((*pp-destination* destination)
        (*pp-column* (or (if (typep destination 'egcl-gray-streams:fundamental-character-output-stream)
                            (egcl-gray-streams:stream-line-column destination)
                            (egcl::%pprint-native-column destination))
                        0))
        (*pp-spaces* 0) (*pp-prefixes* nil) (*pp-suffixes* nil)
        (*pp-lines* 0) (*pp-stop* (gensym)))
    (catch *pp-stop* (%pp-render-block node))
    (%pp-flush-spaces)))

(defun %pp-output-stream (stream)
  (let ((stream (cond ((null stream) *standard-output*) ((eq stream t) *terminal-io*) (t stream))))
    (unless (and (streamp stream) (output-stream-p stream))
      (error 'type-error :datum stream :expected-type 'stream))
    stream))

(defun %pp-pop (state stream exit)
  (let ((remaining (first state)) (count (second state)))
    (cond ((not (listp remaining))
           (write-string ". " stream) (write remaining :stream stream) (throw exit nil))
          ((and *print-length* (not *print-readably*) (>= count *print-length*))
           (write-string "..." stream) (throw exit nil))
          ((and (plusp count) (egcl::%pprint-circle :shared remaining))
           (write-string ". " stream) (write remaining :stream stream) (throw exit nil)))
    (incf (second state))
    (pop (first state))))

(defun %pp-call (destination object prefix per-line suffix function)
  (check-type prefix string)
  (check-type suffix string)
  (setf destination (%pp-output-stream destination))
  (unless (and (streamp destination) (output-stream-p destination))
    (error 'type-error :datum destination :expected-type 'stream))
  (egcl::%pprint-circle :enter object)
  (unwind-protect
       (cond ((not (listp object)) (write object :stream destination))
             ((and *print-level* (not *print-readably*) (<= *print-level* 0))
              (write-char #\# destination))
             (t
              (let ((mark (egcl::%pprint-circle :mark object)))
                (when (not (zerop mark))
                  (format destination "#~D~A" (abs mark) (if (minusp mark) "#" "=")))
                (unless (minusp mark)
                  (let* ((nested (typep destination '%pretty-stream))
                         (stream (if nested destination (make-instance '%pretty-stream)))
                         (exit (gensym)) (state (list object 0))
                         (*print-level* (and *print-level* (not *print-readably*) (1- *print-level*))))
                    (push nil (%pp-frames stream))
                    (incf (%pp-column stream) (length prefix))
                    (unwind-protect
                         (catch exit (funcall function stream state exit))
                      (let ((node (list :block prefix per-line suffix
                                        (nreverse (pop (%pp-frames stream))))))
                        (incf (%pp-column stream) (length suffix))
                        (if nested (%pp-enqueue stream node) (%pp-render node destination)))))))))
    (egcl::%pprint-circle :exit nil))
  nil)

(in-package :common-lisp)

(defmacro pprint-logical-block ((stream object &rest options) &body body)
  "Group output into a logical block with lexical list traversal and print limits."
  (unless (symbolp stream) (error "PPRINT-LOGICAL-BLOCK requires a stream variable"))
  (let ((binding (cond ((null stream) '*standard-output*) ((eq stream t) '*terminal-io*) (t stream)))
        (value (gensym)) (state (gensym)) (exit (gensym)) (output (gensym))
        (bindings nil) (keywords nil))
    (loop while options do
      (let ((key (pop options)) (temporary (gensym)))
        (unless (and options (member key '(:prefix :per-line-prefix :suffix)))
          (error "Invalid PPRINT-LOGICAL-BLOCK options"))
        (push (list temporary (pop options)) bindings)
        (unless (assoc key keywords) (push (cons key temporary) keywords))))
    (when (and (assoc :prefix keywords) (assoc :per-line-prefix keywords))
      (error "PPRINT-LOGICAL-BLOCK cannot combine :PREFIX and :PER-LINE-PREFIX"))
    `(let* ((,value ,object) ,@(nreverse bindings))
       (egcl-pprint::%pp-call ,binding ,value
                      ,(or (cdr (assoc :prefix keywords)) (cdr (assoc :per-line-prefix keywords)) "")
                      ,(not (null (assoc :per-line-prefix keywords)))
                      ,(or (cdr (assoc :suffix keywords)) "")
                      (lambda (,output ,state ,exit)
                        (let ((,binding ,output))
                         (macrolet ((pprint-pop () '(egcl-pprint::%pp-pop ,state ,binding ,exit))
                                   (pprint-exit-if-list-exhausted ()
                                     '(when (null (first ,state)) (throw ,exit nil))))
                          ,@body)))))))

(defmacro pprint-pop ()
  (error "PPRINT-POP requires a lexical PPRINT-LOGICAL-BLOCK"))

(defmacro pprint-exit-if-list-exhausted ()
  (error "PPRINT-EXIT-IF-LIST-EXHAUSTED requires a lexical PPRINT-LOGICAL-BLOCK"))

(defun pprint-newline (kind &optional stream)
  "Queue a conditional newline in the current pretty-printing stream."
  (unless (member kind '(:linear :fill :miser :mandatory))
    (error 'type-error :datum kind :expected-type '(member :linear :fill :miser :mandatory)))
  (let ((stream (egcl-pprint::%pp-output-stream stream)))
    (when (and *print-pretty* (typep stream 'egcl-pprint::%pretty-stream))
      (egcl-pprint::%pp-enqueue stream (list :newline kind))))
  nil)

(defun pprint-indent (relative-to n &optional stream)
  (unless (member relative-to '(:block :current))
    (error 'type-error :datum relative-to :expected-type '(member :block :current)))
  (check-type n real)
  (let ((stream (egcl-pprint::%pp-output-stream stream)))
    (when (and *print-pretty* (typep stream 'egcl-pprint::%pretty-stream))
      (egcl-pprint::%pp-enqueue stream (list :indent relative-to (truncate n)))))
  nil)

(defun pprint-fill (stream object &optional (colon-p t) at-sign-p)
  "Print list elements with fill-style line breaks."
  (declare (ignore at-sign-p))
  (pprint-logical-block (stream object :prefix (if colon-p "(" "") :suffix (if colon-p ")" ""))
    (pprint-exit-if-list-exhausted)
    (loop (write (pprint-pop) :stream stream)
          (pprint-exit-if-list-exhausted)
          (write-char #\Space stream)
          (pprint-newline :fill stream))))

(defun pprint-linear (stream object &optional (colon-p t) at-sign-p)
  "Print list elements with linear-style line breaks."
  (declare (ignore at-sign-p))
  (pprint-logical-block (stream object :prefix (if colon-p "(" "") :suffix (if colon-p ")" ""))
    (pprint-exit-if-list-exhausted)
    (loop (write (pprint-pop) :stream stream)
          (pprint-exit-if-list-exhausted)
          (write-char #\Space stream)
          (pprint-newline :linear stream))))

(in-package :cl-user)
