;;; SPDX-License-Identifier: GPL-3.0-or-later WITH Classpath-exception-2.0
(deftype octet-alias () '(unsigned-byte 8))
(deftype nested-octet () 'octet-alias)
(dolist (pair '(((unsigned-byte 8) (unsigned-byte 8))
                (octet-alias (unsigned-byte 8))
                ((unsigned-byte 8) nested-octet)
                ((signed-byte 16) (signed-byte 16))
                ((unsigned-byte 0) (unsigned-byte 0))))
  (assert (equal '(t t) (multiple-value-list (subtypep (first pair) (second pair))))))
(assert (not (subtypep '(unsigned-byte 16) '(unsigned-byte 8))))
(assert (not (subtypep '(signed-byte 8) '(unsigned-byte 8))))
(let ((a (list 1)) (b (list 1)))
  (assert (not (subtypep (list 'eql a) (list 'eql b)))))
(format t "BYTE-TYPES-OK~%")
