;;; SPDX-License-Identifier: GPL-3.0-or-later WITH Classpath-exception-2.0
(defclass sequence-octets (egcl-gray-streams:fundamental-binary-input-stream)
  ((remaining :initform '(0 128 255))))
(defmethod egcl-gray-streams:stream-read-byte ((s sequence-octets))
  (if (slot-value s 'remaining) (pop (slot-value s 'remaining)) :eof))
(defclass sequence-chars (egcl-gray-streams:fundamental-character-input-stream)
  ((remaining :initform '(#\a #\b))))
(defmethod egcl-gray-streams:stream-read-char ((s sequence-chars))
  (if (slot-value s 'remaining) (pop (slot-value s 'remaining)) :eof))
(let ((v (make-array 5 :initial-element -1)))
  (assert (= 4 (read-sequence v (make-instance 'sequence-octets) :start 1)))
  (assert (equalp v #(-1 0 128 255 -1))))
(let ((v (list -1 -1 -1 -1)))
  (assert (= 2 (funcall #'read-sequence v (make-instance 'sequence-octets) :end 2)))
  (assert (equal v '(0 128 -1 -1))))
(let ((v (make-string 4 :initial-element #\-)))
  (assert (= 3 (read-sequence v (make-instance 'sequence-chars) :start 1)))
  (assert (string= v "-ab-")))
(format t "GRAY-SEQUENCE-OK~%")
