;;; SPDX-License-Identifier: GPL-3.0-or-later WITH Classpath-exception-2.0
(deftype alias-character () 'character)
(deftype nested-character () 'alias-character)
(deftype alias-bit () 'bit)
(let ((s (make-array 3 :element-type 'nested-character :initial-element #\a)))
  (assert (stringp s))
  (assert (string= s "aaa"))
  (let ((view (make-array 2 :element-type 'alias-character :displaced-to s)))
    (assert (stringp view))
    (assert (string= view "aa"))))
(let ((s (make-array 2 :element-type 'alias-character :adjustable t
                       :fill-pointer 0)))
  (assert (stringp s))
  (vector-push-extend #\x s)
  (assert (string= s "x")))
(let ((bits (make-array 3 :element-type 'alias-bit :initial-element 1)))
  (assert (bit-vector-p bits))
  (assert (equalp bits #*111)))
(format t "ARRAY-TYPE-ALIASES-OK~%")
