;;; SPDX-License-Identifier: GPL-3.0-or-later WITH Classpath-exception-2.0
(in-package :egcl-apk)

(defun safe-entry-name-p (name)
  (and (stringp name) (plusp (length name)) (not (find (char name 0) "/\\"))
       (not (find #\\ name)) (not (find #\Null name))
       (every (lambda (part) (and (plusp (length part)) (not (member part '("." "..") :test #'equal))))
              (uiop:split-string name :separator "/"))))
(defun zip-sections (entries)
  (unless (< (length entries) 65535) (error "ZIP64 is not supported"))
  (let ((locals nil) (central nil) (offset 0) (seen nil))
    (dolist (entry entries)
      (let* ((name (car entry)) (data (cdr entry)))
        (unless (and (safe-entry-name-p name) (not (member name seen :test #'equal)))
          (error "Unsafe or duplicate APK entry: ~S" name))
        (push name seen)
        (let* ((encoded (utf8 name)) (size (length data)) (crc (crc32 data))
               (alignment (if (and (uiop:string-prefix-p "lib/" name) (uiop:string-suffix-p name ".so")) 16384 4))
               (padding (mod (- (+ offset 30 (length encoded) 4)) alignment))
               (extra (bytes (u16 #xffff) (u16 padding)
                             (make-array padding :element-type '(unsigned-byte 8) :initial-element 0)))
               (local (bytes (u32 #x04034b50) (u16 20) (u16 #x800) (u16 0) (u16 0) (u16 #x21)
                             (u32 crc) (u32 size) (u32 size) (u16 (length encoded)) (u16 (length extra))
                             encoded extra data)))
          (push (bytes (u32 #x02014b50) (u16 20) (u16 20) (u16 #x800) (u16 0)
                       (u16 0) (u16 #x21) (u32 crc) (u32 size) (u32 size)
                       (u16 (length encoded)) (u16 0) (u16 0) (u16 0) (u16 0) (u32 0) (u32 offset) encoded) central)
          (push local locals) (incf offset (length local)))))
    (let* ((directory (apply #'bytes (nreverse central)))
           (end (bytes (u32 #x06054b50) (u16 0) (u16 0) (u16 (length entries)) (u16 (length entries))
                       (u32 (length directory)) (u32 offset) (u16 0))))
      (list (apply #'bytes (nreverse locals)) directory end))))
(defun write-apk (path entries &key identity)
  "Write stored, aligned ZIP entries; IDENTITY enables APK v2 signing."
  (destructuring-bind (local directory end) (zip-sections entries)
    (let ((block (if identity (signing-block identity (list local directory end)) #())))
      (replace end (u32 (+ (length local) (length block))) :start1 16)
      (ensure-directories-exist path)
      (with-open-file (out path :direction :output :element-type '(unsigned-byte 8)
                               :if-exists :supersede :if-does-not-exist :create)
        (dolist (part (list local block directory end)) (write-sequence part out)))))
  path)

(defun json-file (path)
  (let ((json:*json-identifier-name-to-lisp* #'identity)
        (json:*identifier-name-to-key* #'identity))
    (json:decode-json-from-string (uiop:read-file-string path))))
(defun field (name object)
  (or (cdr (assoc name object :test #'equal)) (error "Missing runtime field: ~A" name)))
(defun project-config (path)
  (with-open-file (in path)
    (let* ((*read-eval* nil) (config (read in nil nil)))
      (unless (and (listp config) (evenp (length config)) (eq :eof (read in nil :eof)))
        (error "APK configuration must be one property list"))
      (loop for key in config by #'cddr do
        (unless (member key '(:package :label :version-code :version-name :min-sdk :target-sdk
                             :debuggable :permissions :hosts :runtime-api :runtime-version))
          (error "Unsupported APK configuration key: ~S" key)))
      config)))
(defun runtime-entry (runtime metadata host)
  (let* ((abi (cond ((equal host "aarch64-linux-android") "arm64-v8a")
                    ((equal host "x86_64-linux-android") "x86_64")
                    (t (error "Unsupported Android host: ~S" host))))
         (data (read-bytes (merge-pathnames (format nil "~A/libegcl_android.so" host) runtime)))
         (host-info (field host (field "hosts" metadata))))
    (unless (and (>= (length data) 20) (equalp (subseq data 0 6) #(127 69 76 70 2 1))
                 (= (read-le data 18 2) (if (equal abi "arm64-v8a") 183 62))
                 (equal abi (field "abi" host-info)))
      (error "Wrong ELF runtime for ~A" host))
    (unless (string-equal (ironclad:byte-array-to-hex-string (sha256 data)) (field "sha256" host-info))
      (error "Runtime checksum mismatch for ~A" host))
    (cons (format nil "lib/~A/libegcl_android.so" abi) data)))
(defun asset-entries (project runtime)
  (let* ((root (truename (merge-pathnames "assets/" project))) (entries nil))
    (when (uiop:subdirectories root) (error "This initial APK builder supports flat assets only"))
    (dolist (path (uiop:directory-files root))
      (let ((name (file-namestring path)))
        (unless (and (safe-entry-name-p name) (not (find #\Newline name)) (not (find #\Return name))
                     (uiop:subpathp (truename path) root))
          (error "Invalid or escaping asset: ~A" path))
        (when (member name '("android.lisp" "egcl-assets.txt") :test #'equal)
          (error "~A is supplied by the runtime, not the app" name))
        (with-open-file (s path :element-type '(unsigned-byte 8))
          (when (> (file-length s) (* 64 1024 1024)) (error "Asset too large: ~A" name)))
        (push (cons (concatenate 'string "assets/" name) (read-bytes path)) entries)))
    (unless (assoc "assets/app.lisp" entries :test #'equal) (error "Missing assets/app.lisp"))
    (push (cons "assets/android.lisp" (read-bytes (merge-pathnames "templates/android.lisp" runtime))) entries)
    (setf entries (sort entries #'string< :key #'car))
    (let ((index (format nil "egcl-android-assets-v1~%~{~A~%~}" (mapcar (lambda (e) (subseq (car e) 7)) entries))))
      (append entries (list (cons "assets/egcl-assets.txt" (utf8 index)))))))
(defun build-apk (project runtime &key output identity-path)
  "Package an apk.sexp project with the prebuilt Android RPM, without SDK tools."
  (let* ((project (uiop:ensure-directory-pathname (truename project)))
         (runtime (uiop:ensure-directory-pathname (truename runtime)))
         (config (project-config (merge-pathnames "apk.sexp" project)))
         (metadata (json-file (merge-pathnames "runtime.json" runtime)))
         (hosts (getf config :hosts '("aarch64-linux-android")))
         (output (or output (merge-pathnames "build/android-egl.apk" project)))
         (identity-path (or identity-path (merge-pathnames ".egcl-apk-key" project))))
    (unless (and (= (field "api" metadata) 4) (= (getf config :runtime-api 4) 4))
      (error "This builder requires Android runtime API 4"))
    (when (and (getf config :runtime-version)
               (not (equal (getf config :runtime-version) (field "version" metadata))))
      (error "Android runtime version differs from apk.sexp"))
    (unless (and (listp hosts) hosts (= (length hosts) (length (remove-duplicates hosts :test #'equal))))
      (error "HOSTS must be a nonempty list of distinct Android host names"))
    (let* ((options (loop for (key value) on config by #'cddr
                         unless (member key '(:hosts :runtime-api :runtime-version)) append (list key value)))
           (entries (append (list (cons "AndroidManifest.xml" (apply #'manifest options)))
                            (mapcar (lambda (host) (runtime-entry runtime metadata host)) hosts)
                            (asset-entries project runtime)))
           (identity (if (probe-file identity-path) (load-identity identity-path) (create-identity identity-path))))
      (write-apk output entries :identity identity)
      (format t "APK: ~A~%Signer SHA256: ~A~%" output
              (ironclad:byte-array-to-hex-string (sha256 (signing-identity-certificate identity))))
      output)))
