(require :asdf)
;; Read just CL-FAD's GETENV definition, selecting each portability branch.
;; The rest of the enclosing EVAL-WHEN mentions Alexandria's IF-LET.
(unless (find-package "ALEXANDRIA")
  (make-package "ALEXANDRIA" :use nil)
  (export (intern "IF-LET" "ALEXANDRIA") "ALEXANDRIA"))
(defparameter *source* (uiop:getenv "CL_FAD_SOURCE"))
(defparameter *mode* (uiop:getenv "CL_FAD_MODE"))
(defparameter *uiop-package* (find-package "UIOP"))
(defparameter *uiop-name* (package-name *uiop-package*))
(defparameter *uiop-nicknames* (package-nicknames *uiop-package*))
(unless (equal *mode* "native") (setf *features* nil))
(when (equal *mode* "absent")
  (rename-package *uiop-package* "CL-FAD-TEST-HIDDEN-UIOP" nil)
  (assert (null (find-package "UIOP"))))
(with-open-file (stream *source*)
  (loop for form = (read stream nil nil)
        while form
        when (and (consp form) (eq (first form) 'eval-when))
          do (eval (third form)) (return)))
(if (equal *mode* "absent")
    (assert (handler-case (progn (getenv "EGCL_FAD_VALUE") nil)
              (error () t)))
    (progn
      (assert (equal (getenv "EGCL_FAD_VALUE") "cl-fad test value"))
      (assert (equal (getenv "EGCL_FAD_EMPTY") ""))
      (assert (null (getenv "EGCL_FAD_UNSET_892481")))))
(when (equal *mode* "absent")
  (rename-package *uiop-package* *uiop-name* *uiop-nicknames*))
(format t "CL-FAD-GETENV-PASS: ~A~%" *mode*)
(uiop:quit 0)
