(require :asdf)
(asdf:initialize-source-registry '(:source-registry :ignore-inherited-configuration))
(asdf:initialize-output-translations
 (list :output-translations (list t (uiop:getenv "EGCL_PORT_CACHE")) :ignore-inherited-configuration))
(load (uiop:getenv "EGCL_PORT_RUNTIME"))
(setf ocicl-runtime:*local-only* t ocicl-runtime:*download* nil)
(asdf:load-system :cl-fad)
(assert (equal (cl-fad::getenv "EGCL_FAD_VALUE") "cl-fad test value"))
(assert (equal (cl-fad::getenv "EGCL_FAD_EMPTY") ""))
(assert (null (cl-fad::getenv "EGCL_FAD_UNSET_892481")))
(assert (null (cl-fad::directory-from-environment "EGCL_FAD_EMPTY")))
(assert (null (cl-fad::directory-from-environment "EGCL_FAD_UNSET_892481")))
(assert (equal (namestring (cl-fad::get-default-temporary-directory))
               (uiop:getenv "TMPDIR")))
(format t "CL-FAD-LOAD-PASS~%")
(uiop:quit 0)
