[package]
name = "bliss-cli"
description = "Bliss Common Lisp CLI: REPL, image loading, entry point"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bliss-rt.workspace = true
bliss-compiler.workspace = true
bliss-stdlib.workspace = true
