;; Windows physical pathnames: components and namestrings must agree.
(defun check-windows-path (text host device directory name type)
  (let ((p (parse-namestring text)))
    (assert (not (typep p 'logical-pathname)))
    (assert (equal (pathname-host p) host))
    (assert (equal (pathname-device p) device))
    (assert (equal (pathname-directory p) directory))
    (assert (equal (pathname-name p) name))
    (assert (equal (pathname-type p) type))
    (assert (equal p (parse-namestring (namestring p))))))
(check-windows-path "C:/Work/demo.lisp" nil "C" '(:absolute "Work") "demo" "lisp")
(check-windows-path "c:demo.lisp" nil "C" nil "demo" "lisp")
(check-windows-path "C:/" nil "C" '(:absolute) nil nil)
(check-windows-path "C:" nil "C" nil nil nil)
(check-windows-path "/Work/demo.lisp" nil nil '(:absolute "Work") "demo" "lisp")
(check-windows-path "relative/demo.lisp" nil nil '(:relative "relative") "demo" "lisp")
(check-windows-path "//server/share/Work/demo.lisp" "server" "share" '(:absolute "Work") "demo" "lisp")
(check-windows-path "//server/share" "server" "share" '(:absolute) nil nil)
(check-windows-path "\\\\?\\C:\\Work\\demo.lisp" nil "C" '(:absolute "Work") "demo" "lisp")
(check-windows-path "\\\\?\\UNC\\server\\share\\Work\\demo.lisp" "server" "share" '(:absolute "Work") "demo" "lisp")
(assert (string= (namestring (make-pathname :device "C" :directory '(:absolute "Work")
                                          :name "demo" :type "lisp")) "C:/Work/demo.lisp"))
(assert (string= (namestring (make-pathname :device "C" :directory '(:relative "Work")
                                          :name "demo" :type "lisp")) "C:Work/demo.lisp"))
(assert (string= (namestring (make-pathname :host "server" :device "share"
                          :directory '(:absolute "Work") :name "demo" :type "lisp"))
                 "//server/share/Work/demo.lisp"))
(dolist (case '(("child" "C:/base/default.lisp" "C:/base/child.lisp")
                ("C:child" "C:/base/default.lisp" "C:/base/child.lisp")
                ("D:child" "C:/base/default.lisp" "D:child.lisp")
                ("/root/child" "C:/base/default.lisp" "C:/root/child.lisp")
                ("D:/root/child" "C:/base/default.lisp" "D:/root/child.lisp")
                ("child" "//server/share/base/default.lisp" "//server/share/base/child.lisp")
                ("/root/child" "//server/share/base/default.lisp" "//server/share/root/child.lisp")
                ("C:child" "//server/share/base/default.lisp" "C:child.lisp")
                ("//other/share/child" "//server/share/base/default.lisp" "//other/share/child.lisp")))
  (assert (string= (namestring (merge-pathnames (first case) (second case))) (third case))))
(let ((a #p"C:/Work/Demo.LISP") (b #p"c:/work/demo.lisp"))
  (assert (equal a b))
  (assert (= (sxhash a) (sxhash b)))
  (let ((table (make-hash-table :test 'equal)))
    (setf (gethash a table) 42)
    (assert (= (gethash b table) 42))))
(assert (pathname-match-p #p"C:/Work/Demo.LISP" #p"c:/work/*.lisp"))
(assert (not (pathname-match-p #p"C:/work/demo.lisp" #p"D:/work/*.lisp")))
(assert (string= (directory-namestring #p"C:/Work/demo.lisp") "C:/Work/"))
(assert (string= (namestring (make-pathname :host (copy-seq "server") :device "share"
                                           :name "demo" :type "lisp"))
                 "//server/share/demo.lisp"))
(assert (equal (pathname-directory (make-pathname :host "server" :device "share")) '(:absolute)))
(assert (equal (pathname-device (make-pathname :device "c")) "C"))
(assert (equal (pathname-host (parse-namestring "//server/share/file" nil)) "server"))
(assert (handler-case (progn (make-pathname :host "server" :device "share"
                            :directory '(:relative "Work")) nil) (file-error () t)))
(assert (string= (namestring (translate-pathname #p"C:/Work/Demo.LISP"
                                 #p"c:/work/*.lisp" #p"D:/Output/*.fasl"))
                 "D:/Output/Demo.fasl"))
(format t "WINDOWS-PATHNAMES-OK~%")
