;;;; Minimal EGL lifecycle, with all foreign calls in Lisp.
(defpackage :egcl-egl (:use :cl) (:export :with-window :clear :swap))
(in-package :egcl-egl)
(defparameter *egl* (egcl-ffi:load-foreign-library "libEGL.so"))
(defparameter *gles* (egcl-ffi:load-foreign-library "libGLESv2.so"))
(defvar *display*)
(defvar *surface*)
(defun call-egl (name ret types &rest args)
  (android:foreign-call *egl* name ret types args))
(defun clear (red green blue)
  (android:foreign-call *gles* "glClearColor" :void '(:float :float :float :float)
                        (list (float red 1.0) (float green 1.0) (float blue 1.0) 1.0))
  (android:foreign-call *gles* "glClear" :void '(:int) (list #x4000)))
(defun swap ()
  (unless (plusp (call-egl "eglSwapBuffers" :int '(:pointer :pointer) *display* *surface*))
    (error "eglSwapBuffers failed")))
(defun check-pointer (pointer what)
  (when (egcl-ffi:null-pointer-p pointer) (error "~A failed" what))
  pointer)
(defun check-status (status what)
  (unless (plusp status) (error "~A failed" what)))
(defun run-window (window draw)
  (let* ((null (egcl-ffi:null-pointer))
         (*display* (check-pointer (call-egl "eglGetDisplay" :pointer '(:pointer) null) "eglGetDisplay"))
         (*surface* null) (context null)
         (attrs (egcl-ffi:foreign-alloc 52))
         (config-out (egcl-ffi:foreign-alloc 8))
         (count (egcl-ffi:foreign-alloc 4))
         (visual (egcl-ffi:foreign-alloc 4)))
    (unwind-protect
        (progn
          (check-status (call-egl "eglInitialize" :int '(:pointer :pointer :pointer) *display* null null) "eglInitialize")
          (loop for v in '(#x3033 4 #x3040 4 #x3024 8 #x3023 8 #x3022 8 #x3021 8 #x3038)
                for i from 0 do (egcl-ffi:mem-set v attrs :int (* i 4)))
          (egcl-ffi:mem-set 0 count :int)
          (check-status (call-egl "eglChooseConfig" :int '(:pointer :pointer :pointer :int :pointer)
                                  *display* attrs config-out 1 count) "eglChooseConfig")
          (unless (plusp (egcl-ffi:mem-ref count :int)) (error "No EGL configuration"))
          (let ((config (egcl-ffi:mem-ref config-out :pointer)))
            (check-status (call-egl "eglGetConfigAttrib" :int '(:pointer :pointer :int :pointer)
                                    *display* config #x302E visual) "eglGetConfigAttrib")
            (let ((android-lib (egcl-ffi:load-foreign-library "libandroid.so")))
              (android:foreign-call android-lib "ANativeWindow_setBuffersGeometry" :int
                                    '(:pointer :int :int :int)
                                    (list window 0 0 (egcl-ffi:mem-ref visual :int))))
            (setf *surface* (check-pointer
                            (call-egl "eglCreateWindowSurface" :pointer '(:pointer :pointer :pointer :pointer)
                                      *display* config window null) "eglCreateWindowSurface"))
            (egcl-ffi:mem-set #x3098 attrs :int 0)
            (egcl-ffi:mem-set 2 attrs :int 4)
            (egcl-ffi:mem-set #x3038 attrs :int 8)
            (setf context (check-pointer
                           (call-egl "eglCreateContext" :pointer '(:pointer :pointer :pointer :pointer)
                                     *display* config null attrs) "eglCreateContext"))
            (check-status (call-egl "eglMakeCurrent" :int '(:pointer :pointer :pointer :pointer)
                                    *display* *surface* *surface* context) "eglMakeCurrent")
            (funcall draw)))
      (call-egl "eglMakeCurrent" :int '(:pointer :pointer :pointer :pointer) *display* null null null)
      (unless (egcl-ffi:null-pointer-p context)
        (call-egl "eglDestroyContext" :int '(:pointer :pointer) *display* context))
      (unless (egcl-ffi:null-pointer-p *surface*)
        (call-egl "eglDestroySurface" :int '(:pointer :pointer) *display* *surface*))
      (call-egl "eglTerminate" :int '(:pointer) *display*)
      (dolist (pointer (list attrs config-out count visual)) (egcl-ffi:foreign-free pointer)))))
(defmacro with-window ((window) &body body) `(run-window ,window (lambda () ,@body)))
(in-package :cl-user)
