(require :asdf)
(asdf:initialize-source-registry '(:source-registry :ignore-inherited-configuration))
(asdf:initialize-output-translations
 (list :output-translations (list t (uiop:getenv "EGCL_PORT_CACHE")) :ignore-inherited-configuration))
(load (uiop:getenv "EGCL_PORT_RUNTIME"))
(setf ocicl-runtime:*local-only* t ocicl-runtime:*download* nil)
(asdf:load-system :atomics)
(load (asdf:system-relative-pathname :atomics "egcl-tests.lisp"))
(asdf:load-system :cl-cancel)
(cl-cancel::ensure-atomic-initialized)
(assert (not (null cl-cancel::*timer-initialized*)))
(assert (not (eq :creating cl-cancel::*timer-initialized*)))
(format t "CL-CANCEL-ATOMIC-INIT-PASS~%")
(uiop:quit 0)
