(defmacro zapf (place expr)
  (multiple-value-bind (temps exprs stores store-expr access-expr)
      (get-setf-expansion place)
    `(let* (,@(mapcar #'list temps exprs)
            (,(car stores) (let ((% ,access-expr)) ,expr)))
       ,store-expr)))
(defstruct ball (x 0 :type fixnum))
(defun k-manual (b n) (dotimes (i n) (setf (ball-x b) (+ (ball-x b) 1))) (ball-x b))
(defun k-zapf   (b n) (dotimes (i n) (zapf (ball-x b) (+ % 1)))          (ball-x b))
(defun k-incf   (b n) (dotimes (i n) (incf (ball-x b)))                  (ball-x b))
(defun k-empty  (b n) (declare (ignore b)) (let ((a 0)) (dotimes (i n) (setq a i)) a))
(dolist (f '(k-empty k-manual k-zapf k-incf))
  (let ((b (make-ball))) (dotimes (w 300) (funcall f b 50)) (funcall f b 300000))
  (let* ((b (make-ball)) (n 2000000) (s (get-internal-real-time)) (r (funcall f b n)))
    (format t "~8,2f ns/iter  ~a  (result ~a)~%"
            (/ (* 1000000.0 (- (get-internal-real-time) s)) n) f r)))
